# Initiate by doing
# docker compose -f postgre.yml up

version: "3.8"
name: postgre_pg-admin
services:
  db:
    container_name: postgres_container
    image: postgres:15.2-alpine
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: my_db # Don't forget to change this
    ports:
      - "5432:5432"
    networks:
      - database-network
    
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    networks:
      - database-network

networks:
  database-network: